spring:
  application:
    name: crud-spring
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true

server:
  error:
    include-stacktrace: never
    include-message: never